version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: junction.proxy.rlwy.net
      PMA_PORT: 13109
      PMA_USER: root
      PMA_PASSWORD: OyKSYLhjJdkWbncqOUPzUqnNVxAAiBVj
